[tox]
envlist = pre-commit,docs,mypy,twine,min,py39,py310,py311,py312,py313

[testenv]
deps =
    pytest==8.3.5
    pytest-cov==6.1.1
    pytest-twisted==1.14.3
commands =
    pytest \
    {posargs: \
        --cov scrapy_crawl_maps \
        -vv \
        scrapy_crawl_maps \
        tests \
    }

[testenv:min]
basepython = python3.9
deps =
    {[testenv]deps}
    itemadapter==0.8.0
    jmespath==0.9.5
    pydantic==2.4.0
    scrapy==2.13.0
    scrapy-poet==0.26.0
    scrapy-spider-metadata==0.1.1

[testenv:mypy]
deps =
    {[testenv]deps}
    mypy==1.15.0
    types-jmespath==1.0.2.20240106
    typing-extensions==4.13.2
commands = mypy scrapy_crawl_maps tests

[testenv:pre-commit]
deps =
    pre-commit==4.2.0
commands = pre-commit run --all-files --show-diff-on-failure

[testenv:twine]
deps =
    twine==6.1.0
    build==1.2.2.post1
commands =
    python -m build --sdist
    twine check dist/*

[testenv:docs]
changedir = docs
deps =
    -rdocs/requirements.txt
commands =
    sphinx-build -W -b html . {envtmpdir}/html
